//! Build script: generates the embedded built-in rule list from the
//! `rules/` directory so the directory is the single source of truth.
//!
//! Before this script existed, `built_in_packs()` hand-maintained an
//! `include_str!` list; rules added to `rules/` but not to that list shipped
//! as files yet never ran in scans, and the fixture CI gate (which iterates
//! the embedded list) silently skipped them. Generation makes drift
//! structurally impossible: a rule file present in `rules/` is compiled into
//! the binary, and the fixture gate exercises exactly that set.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let rules_root = Path::new(&manifest_dir).join("rules");

    let mut packs = Vec::new();
    let mut entries: Vec<PathBuf> = fs::read_dir(&rules_root)
        .unwrap_or_else(|error| {
            panic!(
                "build.rs: unable to read rules directory '{}': {error}",
                rules_root.display()
            )
        })
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| {
            path.is_dir()
                // Skip hidden directories (tool state such as `.mimosa` must
                // never be mistaken for a rule pack).
                && path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(|name| !name.starts_with('.'))
        })
        .collect();
    entries.sort();

    for pack_dir in &entries {
        let manifest = pack_dir.join("pack.toml");
        if !manifest.is_file() {
            panic!(
                "build.rs: rule pack directory '{}' has no pack.toml",
                pack_dir.display()
            );
        }
        // Built-in packs use the flat layout: `*.rule.toml` directly inside the
        // pack directory (`rules/<pack>/<rule>.rule.toml`). Only direct
        // children are collected — `fixtures/` and other subdirectories never
        // contribute rules.
        let mut rule_files: Vec<PathBuf> = fs::read_dir(pack_dir)
            .unwrap_or_else(|error| {
                panic!(
                    "build.rs: unable to read pack '{}': {error}",
                    pack_dir.display()
                )
            })
            .filter_map(|entry| entry.ok().map(|entry| entry.path()))
            .filter(|path| {
                path.is_file()
                    && path
                        .file_name()
                        .and_then(|name| name.to_str())
                        .is_some_and(|name| name.ends_with(".rule.toml"))
            })
            .collect();
        rule_files.sort();
        if rule_files.is_empty() {
            panic!(
                "build.rs: rule pack directory '{}' contains no .toml rules",
                pack_dir.display()
            );
        }

        let mut pack_code = String::new();
        pack_code.push_str(&format!(
            "        (\n            include_str!({manifest_literal:?}),\n            &[\n",
            manifest_literal = absolute(&manifest).to_string_lossy()
        ));
        for rule_file in &rule_files {
            let rel = relative(&rules_root, rule_file);
            pack_code.push_str(&format!(
                "                (\"built-in:{rel}\", include_str!({literal:?})),\n",
                literal = absolute(rule_file).to_string_lossy()
            ));
        }
        pack_code.push_str("            ],\n        ),\n");
        packs.push(pack_code);
    }

    let mut generated = String::new();
    generated
        .push_str("// @generated by hawk-core/build.rs from the rules/ directory. Do not edit.\n");
    generated
        .push_str("// The rules directory is the single source of truth: every `*.rule.toml`\n");
    generated.push_str("// under `rules/<pack>/rules/` is compiled into the binary here.\n");
    generated.push_str("pub static BUILT_IN_PACKS: &[(&str, &[(&str, &str)])] = &[\n");
    for pack in &packs {
        generated.push_str(pack);
    }
    generated.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let destination = Path::new(&out_dir).join("builtin_packs.rs");
    fs::write(&destination, generated).unwrap_or_else(|error| {
        panic!(
            "build.rs: unable to write {}: {error}",
            destination.display()
        )
    });

    // Re-run whenever any rule/pack file changes so the embedded set stays current.
    println!("cargo:rerun-if-changed=rules");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Path relative to the `rules/` root, used in diagnostic source labels.
fn relative(rules_root: &Path, path: &Path) -> String {
    path.strip_prefix(rules_root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

/// include_str! paths in the generated file (under OUT_DIR) must be absolute.
fn absolute(path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .unwrap_or_else(|_| PathBuf::from("."))
            .join(path)
    }
}
